# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    name: Metric
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: NyanKaungSet
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Rangoon
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: Nyan Kaung Set
