# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule:
    - cron: "0 0 * * 1,3,5"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/img/github-metric.svg
          token: ${{ secrets.METRIC_TOKEN_1 }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: NyanKaungSet
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Rangoon
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: data, prose, markup, programming
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_colors: rainbow
          plugin_languages_indepth: yes
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 700
          plugin_languages_sections: most-used
          
          plugin_followup: yes
          plugin_followup_sections: user
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 365
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          
          plugin_achievements: yes
          plugin_achievements_threshold: S, A, B, C, X
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
