name: Compact display
on:
  schedule:
    - cron: "0 23 9 9 *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Achievement
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}


          # plugin_achievements: yes
          # plugin_achievements_only: >-
          #  polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
          #  scripter, packager, explorer, infographile, manager
          # plugin_achievements_display: compact
          # plugin_achievements_threshold: X
          
          # Options
          user: NyanKaungSet
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_stargazers: yes
          plugin_pagespeed: no
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }} # Optional but recommended
          plugin_pagespeed_detailed: yes                         # Print detailed audit metrics
          plugin_pagespeed_screenshot: no                        # Display a screenshot of your website
          plugin_pagespeed_url: .user.website                    # Website to audit (defaults to your GitHub linked website)
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }} # Required
          plugin_tweets_limit: 2                            # Limit to 2 tweets
          plugin_tweets_attachments: yes                    # Display tweets attachments (images, preview urls, etc.)
          plugin_tweets_user: .user.twitter                 # Defaults to your GitHub linked twitter username:  
          #plugin_projects: yes
          #plugin_projects_repositories: CodeforcesContestHelper/CodeforcesContestHelper/projects/1 # Display #1 project of lowlighter/metrics repository
          #plugin_projects_limit: 4                                    # Limit to 4 entries
          #plugin_projects_descriptions: yes                           # Display projects descriptions
          plugin_posts: mo
          plugin_posts_source: dev.to      # External source
          plugin_people_user: .github.user # Use same username as GitHub login:
          #plugin_wakatime: yes                                      # (🚧 @master feature)
          #plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          #plugin_wakatime_days: 7                                   # Display last week stats
          #plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          #plugin_wakatime_limit: 4                                  # Show 4 entries per graph:  
          plugin_contributors: yes
          plugin_contributors_base: ""           # Base reference (commit, tag, branch, etc.)
          plugin_contributors_head: master       # Head reference (commit, tag, branch, etc.)
          #plugin_contributors_ignored: bot       # Ignore "bot" user
          plugin_contributors_contributions: yes # Display number of contributions for each contributor
          plugin_achievements: yes
          plugin_achievements_threshold: C       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          #plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_filter: stars:>50  # Only display repositories with 500 stars or more (syntax based on GitHub search query)
          plugin_notable_repositories: yes     # Display repositories name instead of only organization name
          plugin_activity: yes
          plugin_activity_limit: 5    # Limit to 5 events
          plugin_activity_days: 14    # Keep only events from last 14 days (can be set to 0 to disable limitations)
          plugin_activity_filter: all # Show all events (use table above to filter events types)
