name: Detailed Achievement Display
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Achievement
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
          
          # Options
          user: NyanKaungSet
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Yangon
          config_twemoji: yes
          config_animations: yes
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_stargazers: yes
          plugin_people_user: NyanKaungSet
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}     
          plugin_wakatime_days: 7                                   
          plugin_wakatime_sections: time, projects, projects-graphs 
          plugin_wakatime_limit: 4                                  
          # plugin_achievements: yes
          # plugin_achievements_limit: 10
          # plugin_achievements_threshold: C 
          # plugin_achievements_secrets: yes
          plugin_skyline: yes
          plugin_skyline_frames: 120
