name: Fortune
on:
  schedule:
    - cron: "0 23 9 9 *"
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.fortune.svg
            token: ${{ secrets.GITHUB_TOKEN }}
            base: ""
            plugin_fortune: yes

