name: Test
on:
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/img/github-metric-TEST.svg
          token: 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
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: NyanKaungSet
          template: classic
          base: header, activity, community
          config_timezone: Asia/Rangoon
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_days: 10
          plugin_languages_recent_load: 100
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
